### ISSUE TITLE
RunOnce should exit with 0 status code if everything went well

### ISSUE THREAD

**Issue by a86c6f7964** [Cimpress-MCP/fsconsul#15]
currently it exits with -1 or 255 in linux terms.

**Comment by ryansch** [comment]
It appears that fsconsul always exits with -1.

I've coded a simple patch that fixes it in watch.go:
```go
  anyFailure := false

  // Wait for completion of all forked go routines
  for i := 0; i < len(config.Mappings); i++ {
    returnCode := <-returnCodes
    if returnCode != 0 {
      anyFailure = true
    }
    log.Debug(returnCode)
  }

  if anyFailure {
    return -1
  } else {
    return 0
  }
```

I would submit this as a PR but I don't know what idiomatic go looks like yet.  Feel free to refactor.

**Comment by cleung2010** [comment]
Thanks for the report! I have submitted a PR for merging shortly.

**Comment by ryansch** [comment]
Thanks!
