### ISSUE TITLE
change scheme to https 

### ISSUE THREAD

**Issue by SMR39** [Cimpress-MCP/fsconsul#18]
my consul cluster api is accessed from an https endpoint . how do i make fsconsul fetch env from https ?

**Comment by cleung2010** [comment]
You would have to pass in the configuration via a config file, and se `UseTLS` to true. https://github.com/Cimpress-MCP/fsconsul/blob/master/watch.go#L37

**Comment by SMR39** [comment]
Actually i have done that too .. 
Thanks for the reply again

```
{
    "consul": {
        "addr": "consul.blah.com:8500",
        "dc": "dc1",
        "UseTLS": "true"
    },
    "mappings" : [{
        "prefix": "/env/etl/stage",
        "path": "/etc/etl/"
   }]
}
```

```INFO[0000] fsconsul initializing...
ERRO[0000] Failed to parse JSON                          error=json: cannot unmarshal string into Go value of type bool```

I must be doing something wrong !

**Comment by cleung2010** [comment]
You are passing "true" as a string type. It should be `"UseTLS": true`.

**Comment by SMR39** [comment]
duh ... I am being so stupid !! thanks @cleung2010

**Comment by cleung2010** [comment]
No worries!
