### ISSUE TITLE
Latest fsconsul release does not include #17

### ISSUE THREAD

**Issue by ryansch** [Cimpress-MCP/fsconsul#19]
I just reworked our base images to pull from your published download urls and just ran into #15 all over again.  Please cut a new release.

**Comment by calvn** [comment]
I am trying to get a release cut, but it seems that Travis is having timeout issues. Particularly, Travis is not honoring the `exit` command, which leads to a timeout and build failure after 10 minutes.

This might be related:
https://github.com/travis-ci/travis-ci/issues/6590

**Comment by calvn** [comment]
Binaries for v0.6.5 with exit code fixes are [now available](https://bintray.com/cimpress-mcp/Go/fsconsul/v0.6.5).
